# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devmachine < Formula
  desc "Turn a VPS into workspaces you develop in"
  homepage "https://mydevmachine.sh/"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.10.1/devmachine_0.10.1_darwin_amd64.tar.gz"
      sha256 "1fc947778e1cb3e8b85a656165669f2855fdc6f68853677636a5bb0b6beb20c2"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.10.1/devmachine_0.10.1_darwin_arm64.tar.gz"
      sha256 "61aae370d5f1d9aeee276548053aee7b5b67bdea6ae1ab5aee0da9a4844fdf58"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.10.1/devmachine_0.10.1_linux_amd64.tar.gz"
      sha256 "15f9b599722aed5de8f16d37dabc08dc4a79cc45e8b86ae7a8dc08bd75c9d131"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.10.1/devmachine_0.10.1_linux_arm64.tar.gz"
      sha256 "a98a039f2963ed366f6cca4a5913116cf321f05af3bfb79f0631baf6b0cbf109"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  def caveats
    <<~EOS
      Teach your coding agent devmachine (Claude Code, Codex, and others):
        devmachine skills add
      Get started: https://mydevmachine.sh/getting-started/
    EOS
  end

  test do
    system "#{bin}/devmachine", "version"
  end
end
