# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devmachine < Formula
  desc "Turn a VPS into workspaces you develop in"
  homepage "https://mydevmachine.sh/"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.9.0/devmachine_0.9.0_darwin_amd64.tar.gz"
      sha256 "f760a5c2bc68dbe0bc51d5878828b0049d672ce5adf8b31c498c5d9d61278f17"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.9.0/devmachine_0.9.0_darwin_arm64.tar.gz"
      sha256 "a814c17efa668f7edcea1d5edc6af347a3328a2ed309b628aaed1ce322ca088f"

      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.9.0/devmachine_0.9.0_linux_amd64.tar.gz"
      sha256 "01a4fb7337f3b8d2894fdb822f6e7f6276bd60a0e5b04a1394cc7f3784102c1b"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/devmachine/releases/download/v0.9.0/devmachine_0.9.0_linux_arm64.tar.gz"
      sha256 "9faa3deb8c739f9369c08426b44c1050150ba972e5e78c640d71cb12dacc8d4f"
      define_method(:install) do
        bin.install "devmachine"
        bin.install_symlink bin/"devmachine" => "advm"
      end
    end
  end

  def caveats
    <<~EOS
      Teach your coding agent devmachine (Claude Code, Codex, and others):
        devmachine skills add
      Get started: https://mydevmachine.sh/getting-started/
    EOS
  end

  test do
    system "#{bin}/devmachine", "version"
  end
end
