# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SessionShare < Formula
  desc "Share a running tmux session for a limited time, in a browser or over SSH"
  homepage "https://github.com/mydevmachine/session-share"
  version "0.1.0"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mydevmachine/session-share/releases/download/v0.1.0/session-share_darwin_amd64.tar.gz"
      sha256 "efc44a8a5a77347f149857e4125cf856789bfe24f697739f029871ad6e5db50d"

      define_method(:install) do
        bin.install "session-share"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mydevmachine/session-share/releases/download/v0.1.0/session-share_darwin_arm64.tar.gz"
      sha256 "2fc51476b64e9f95d92fede0cbbe5e3d730a974d80786c4eb8798941fcf5334e"

      define_method(:install) do
        bin.install "session-share"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/session-share/releases/download/v0.1.0/session-share_linux_amd64.tar.gz"
      sha256 "90ce670be80d1ee37d58ada12bc765617a1c6ce57631e36b5b32839042e82c2d"
      define_method(:install) do
        bin.install "session-share"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mydevmachine/session-share/releases/download/v0.1.0/session-share_linux_arm64.tar.gz"
      sha256 "b20ce0445be5c473152f501a006a1868f9a719f460e7afdab9b654efc4b5e432"
      define_method(:install) do
        bin.install "session-share"
      end
    end
  end

  test do
    system "#{bin}/session-share", "version"
  end
end
